### ISSUE TITLE
Wake Word Failing to load

### ISSUE THREAD

**Issue by theOriginalWiz** [Thokoop/billy-b-assistant#99]
Just installed and followed the setup steps.  Python is version 3.13, using the recommended speakers and mic from the build menu.

Mic and speakers work in the test menu.  When switching the wake word enabled, I get the following error message:

Jul 14 20:51:01 finn systemd[1]: Started billy.service - Billy Bass Assistant.
Jul 14 20:51:02 finn python[6485]: 🔍 Importing core.providers
Jul 14 20:51:02 finn python[6485]: 🔍 OPENAI_API_KEY set: True
Jul 14 20:51:02 finn python[6485]: 🔍 XAI_API_KEY set: False
Jul 14 20:51:02 finn python[6485]: 🔍 REALTIME_AI_PROVIDER: openai
Jul 14 20:51:02 finn python[6485]: ⚙️ Using third motor: False | Pin profile: new
Jul 14 20:51:02 finn python[6485]: 🔧 Log level set to: VERBOSE
Jul 14 20:51:02 finn python[6485]: 👤 Starting in guest mode
Jul 14 20:51:02 finn python[6485]: 👤 Cleared current user
Jul 14 20:51:03 finn python[6485]: 👤 Identified existing user: Guest (matched 'Guest')
Jul 14 20:51:03 finn python[6485]: 🎭 Loaded persona: finn
Jul 14 20:51:03 finn python[6485]: 🎭 Cleared cache for persona: finn
Jul 14 20:51:03 finn python[6485]: 🎭 Switched to persona: finn
Jul 14 20:51:03 finn python[6485]: 🎭 Loaded guest preferred persona: finn
Jul 14 20:51:03 finn python[6485]: ⚠️ MQTT not configured, skipping.🔢 Enumerating audio devices...
Jul 14 20:51:03 finn python[6485]: 🔍   0: UACDemoV1.0: USB Audio (hw:0,0) (inputs: 0, outputs: 2)
Jul 14 20:51:03 finn python[6485]: ✅ Output device index 0 selected.
Jul 14 20:51:03 finn python[6485]: 🔍   1: USB PnP Sound Device: Audio (hw:1,0) (inputs: 1, outputs: 0)
Jul 14 20:51:03 finn python[6485]: ✅ Input device index 1 selected.
Jul 14 20:51:03 finn python[6485]: ⚠️ Mic does not support 24000Hz; using 48000Hz and resampling to 24000Hz.
Jul 14 20:51:03 finn python[6485]: 🔍   2: sysdefault (inputs: 0, outputs: 128)
Jul 14 20:51:03 finn python[6485]: 🔍   3: front (inputs: 0, outputs: 2)
Jul 14 20:51:03 finn python[6485]: 🔍   4: surround40 (inputs: 0, outputs: 2)
Jul 14 20:51:03 finn python[6485]: 🔍   5: iec958 (inputs: 0, outputs: 2)
Jul 14 20:51:03 finn python[6485]: 🔍   6: spdif (inputs: 0, outputs: 2)
Jul 14 20:51:03 finn python[6485]: 🔍   7: mic (inputs: 128, outputs: 0)
Jul 14 20:51:03 finn python[6485]: 🔍   8: speaker (inputs: 0, outputs: 128)
Jul 14 20:51:03 finn python[6485]: 🔍   9: dmix (inputs: 0, outputs: 2)
Jul 14 20:51:03 finn python[6485]: 🔍   10: default (inputs: 128, outputs: 128)
Jul 14 20:51:03 finn python[6485]: 2026-07-14 20:51:03.050245848 [W:onnxruntime:Default, device_discovery.cc:283 GetGpuDevices] Failed to detect devices under "/sys/class/drm/card1": device_discovery.cc:93 ReadFileContents Failed to open file: "/sys/class/drm/card1/device/vendor"
Jul 14 20:51:03 finn python[6485]: 2026-07-14 20:51:03.050298940 [W:onnxruntime:Default, device_discovery.cc:283 GetGpuDevices] Failed to detect devices under "/sys/class/drm/card0": device_discovery.cc:93 ReadFileContents Failed to open file: "/sys/class/drm/card0/device/vendor"
Jul 14 20:51:03 finn python[6485]: 🧠 Using local/package ONNX support models for openWakeWord preprocessing.
Jul 14 20:51:03 finn python[6485]: ⚠️ Failed to initialize openWakeWord: AudioFeatures.__init__() got an unexpected keyword argument 'wakeword_models'
Jul 14 20:51:03 finn python[6485]: 🎦 Ready. Press button to start a voice session. Press Ctrl+C to quit.
Jul 14 20:51:03 finn python[6485]: 🕐 Waiting for button press...

Let me know if there are more logs I can provide.

**Comment by Thokoop** [comment]
Hi @theOriginalWiz , 

Thank you for your report. Could you check which version of onewakeword you have installed?

In the billy-b-assistant folder:

`source venv/bin/activate`
`python -m pip show openwakeword`

I would expect to see:
`Name: openwakeword`
`Version: 0.6.0 `
....

**Comment by theOriginalWiz** [comment]
Thank you!  Yup,  I think that is it.  I am on version 0.4.0.  Unfortunately, when trying to upgrade to 0.6.0 I am getting a dependency error.  After some research it looks like its not compatible with python 3.13.5.   When I have some time later today I am going to try to reinstall and downgrade python to 3.11.  Will let you know how it goes.  Thank you!

**Comment by theOriginalWiz** [comment]
I reset the virtual env to use python 3.11.15 and was able to reload the requirements including openwakeword 0.6.0.  Works like a charm now, thank you!

**Comment by Thokoop** [comment]
I found a workaround to make it work on 3.13 as well, which I added to the readme.md:
https://github.com/Thokoop/billy-b-assistant/tree/dev#optional-openwakeword-on-python-313
